[font]
size = 11.0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[font.bold]
family = "Noto Sans Mono"
style = "Bold"

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.bold_italic]
family = "Noto Sans Mono"
style = "Bold Italic"

[window]
opacity = 1.0
padding = { x = 10, y = 10 }

[colors.primary]
background = "#f5f5f5"
foreground = "#212121"

[colors.cursor]
text = "#f5f5f5"
cursor = "#212121"

[colors.normal]
black   = "#212121"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#ffffff"

[colors.bright]
black   = "#9e9e9e"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#d6acff"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"
